name: "CI"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '25 2 * * 2'

jobs:

  build_analyze:
    runs-on: windows-2022
    permissions:
      security-events: write
    strategy:
      fail-fast: False
      matrix:
        arch: [x64, arm64]
        build_type: [Debug, Release]
        sdk_version: [19041, 22621]
      # Run unit tests and CodeQL analysis on x64Debug only
        include:
          - arch: x64
            build_type: Debug
            codeql: True
            sdk_version: 19041

    name: build_${{matrix.arch}}_${{matrix.build_type}}_${{matrix.sdk_version}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

    - name: Initialize CodeQL
      if: ${{ matrix.codeql }}
      uses: github/codeql-action/init@42947a340483f03ba47bb1a039b2c519aab3df85 # v3.37.8
      with:
        languages: cpp

    - name: Install Windows SDK
      uses: GuillaumeFalourd/setup-windows10-sdk-action@9979bedbf6ae74f038cc338622ba015942ed2408 # v2.4
      with:
        sdk-version: ${{ matrix.sdk_version }}

    - name: Build
      run: |
        mkdir build && pushd build
        cmake -A ${{ matrix.arch }} -DCMAKE_SYSTEM_VERSION=10.0.${{ matrix.sdk_version }}.0 -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
        cmake --build . --parallel --config ${{ matrix.build_type }}
        popd

    - name: Perform CodeQL Analysis
      if: ${{ matrix.codeql }}
      uses: github/codeql-action/analyze@42947a340483f03ba47bb1a039b2c519aab3df85 # v3.37.8

    - name: Collect test artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: proxy-wifi-test-${{ matrix.arch }}-${{ matrix.build_type }}-${{ matrix.sdk_version }}
        path: build/test/${{ matrix.build_type }}/proxy-wifi-test.exe

  run_unit_tests:
    needs: build_analyze
    runs-on: windows-2022
    steps:
    - name: Download test artifact
      id: download
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: proxy-wifi-test-x64-Debug-19041

    - name: Run tests
      run: ${{steps.download.outputs.download-path}}/proxy-wifi-test.exe -s >> test-logs.txt

    - name: Collect test logs on failure
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: failure()
      with:
        name: test-logs
        path: test-logs.txt
