name: "CI"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '25 2 * * 2'

jobs:
  build_x64_debug_analyze:
    name: Build x64 Debug and Analyze
    # Variables cannot be used there, need to be updated manually to point to the correct branch
    uses: microsoft/proxy_wifi/.github/workflows/build.yml@main
    with:
      arch: x64
      build_type: Debug
      codeql: True
    permissions:
      actions: read
      contents: read
      security-events: write

  build_x64_Release:
    name: Build x64 Release
    # Variables cannot be used there, need to be updated manually to point to the correct branch
    uses: microsoft/proxy_wifi/.github/workflows/build.yml@main
    with:
      arch: x64
      build_type: Release
    permissions:
      actions: read
      contents: read

  build_arm64_debug:
    name: Build ARM64 Debug
    # Variables cannot be used there, need to be updated manually to point to the correct branch
    uses: microsoft/proxy_wifi/.github/workflows/build.yml@main
    with:
      arch: arm64
      build_type: Debug
    permissions:
      actions: read
      contents: read

  build_arm64_release:
    name: Build ARM64 Release
    # Variables cannot be used there, need to be updated manually to point to the correct branch
    uses: microsoft/proxy_wifi/.github/workflows/build.yml@main
    with:
      arch: arm64
      build_type: Release
    permissions:
      actions: read
      contents: read

  run_unit_tests:
    needs: build_x64_debug_analyze
    runs-on: windows-latest
    steps:
    - name: Download test artifact
      id: download
      uses: actions/download-artifact@v2
      with:
        name: proxy-wifi-test-x64-Debug

    - name: Run tests
      run: ${{steps.download.outputs.download-path}}/proxy-wifi-test.exe -s >> test-logs.txt

    - name: Collect test logs on failure
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-logs
        path: test-logs.txt
